### ISSUE TITLE
System.NotSupportedException has been thrown upon start up

### ISSUE THREAD

**Issue by hugefinik** [mrpmorris/blazor-fluxor#121]
After updating my server-side Blazor solution to the 1.3.2.0 .NET 3,1.0-preview4.19579.2 (and up to the 1.4.0), I'v stared to see the following exception upon application start up:

System.NotSupportedException
  HResult=0x80131515
  Message=The collection type 'System.Collections.Generic.IDictionary`2[System.Int64,System.Collections.Generic.IList`1[BlazorMonitorServerApp.Store.VehicleEvent.VehicleResourceEventItem]]' on 'BlazorMonitorServerApp.Store.VehicleEvent.VehicleEventState.DataMap' is not supported.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.JsonSerializer.GetRuntimeClassInfo(Object value, JsonClassInfo& jsonClassInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.HandleDictionary(JsonClassInfo elementClassInfo, JsonSerializerOptions options, Utf8JsonWriter writer, WriteStack& state)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.<InvokeWithDefaultCancellation>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Blazor.Fluxor.ReduxDevTools.ReduxDevToolsInterop.<InitAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
   at Blazor.Fluxor.ReduxDevTools.ReduxDevToolsMiddleware.<InitializeAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Blazor.Fluxor.Store.<InitializeMiddlewares>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Here's the class for the State object that causes this exception:

    public class VehicleEventState
    {
        public VehicleEventState(IDictionary<long, IList<VehicleResourceEventItem>> dataMap, int currentIndex)
        {
            DataMap = dataMap;
            CurrentIndex = currentIndex;
        }

        public int CurrentIndex { get; }
        public IDictionary<long, IList<VehicleResourceEventItem>> DataMap { get; }
    }

    public class VehicleResourceEventItem
    {
        public VehicleResourceEventItem(string formattedJson, string errorMessage, bool isLoaded, bool isLoading, int index, string eventName)
        {
            FormattedJson = formattedJson;
            ErrorMessage = errorMessage;
            IsLoaded = isLoaded;
            IsLoading = isLoading;
            Index = index;
            EventName = eventName;
        }

        public string FormattedJson { get;}
        public string EventName { get; }
        public string ErrorMessage { get; }
        public bool IsLoaded { get; }
        public bool IsLoading { get; }
        public int Index { get; }
    }

Thank you for you help!

**Comment by mrpmorris** [comment]
This is a System.Text.Json error, not sure if it is wasm only or not.

I might switch to Newtonsoft in the meantime.

**Comment by mrpmorris** [comment]
I've investigated this problem. Unfortunately I see `Microsoft.JSInterop.JSRuntime.InvokeAsync` in the callstack, which means that the problem lies in Blazor's use of the new `System.Text.Json` which doesn't seem to support that data type.

https://github.com/dotnet/runtime/issues/32710
